import { localized } from "@/lib/i18n";
import type { Application, EvidenceFact, Job } from "@/lib/types";

export const evidenceFacts: EvidenceFact[] = [
  {
    id: "fact-project-dashboard",
    category: "project",
    title: localized("مشروع لوحة مبيعات", "Sales dashboard project"),
    detail: localized("بناء لوحة لتحليل المبيعات باستخدام Power BI وSQL", "Built a sales analysis dashboard using Power BI and SQL"),
    source: localized("ملف المشروع sales-dashboard.pdf", "Project file sales-dashboard.pdf"),
    status: "confirmed",
    updatedAt: "2026-08-02",
  },
  {
    id: "fact-python-internship",
    category: "experience",
    title: localized("تدريب تعاوني في تحليل البيانات", "Data analytics internship"),
    detail: localized("استخدام Python لتنظيف البيانات وإعداد تقارير أسبوعية", "Used Python to clean data and prepare weekly reports"),
    source: localized("سيرة ذاتية راجعها المستخدم", "User-reviewed CV"),
    status: "confirmed",
    updatedAt: "2026-08-01",
  },
  {
    id: "fact-powerbi",
    category: "certification",
    title: localized("شهادة Power BI", "Power BI certificate"),
    detail: localized("شهادة إتمام مؤكدة في أساسيات Power BI", "Verified completion certificate in Power BI fundamentals"),
    source: localized("power-bi-certificate.pdf", "power-bi-certificate.pdf"),
    status: "confirmed",
    updatedAt: "2026-07-29",
  },
  {
    id: "fact-google-analytics",
    category: "certification",
    title: localized("Google Data Analytics", "Google Data Analytics"),
    detail: localized("شهادة مستخرجة وتحتاج مراجعة الرابط والتاريخ", "Extracted certificate requiring link and date review"),
    source: localized("CV-2026.pdf، الصفحة 2", "CV-2026.pdf, page 2"),
    status: "extracted",
    updatedAt: "2026-08-04",
  },
  {
    id: "fact-degree",
    category: "education",
    title: localized("بكالوريوس نظم معلومات", "BSc in Information Systems"),
    detail: localized("جامعة الملك سعود، 2025", "King Saud University, 2025"),
    source: localized("سيرة ذاتية راجعها المستخدم", "User-reviewed CV"),
    status: "confirmed",
    updatedAt: "2026-07-25",
  },
  {
    id: "fact-english",
    category: "language",
    title: localized("اللغة الإنجليزية", "English language"),
    detail: localized("مستوى مهني — بحسب تصريح المستخدم", "Professional level — user declared"),
    source: localized("إدخال مباشر من المستخدم", "Direct user input"),
    status: "confirmed",
    updatedAt: "2026-07-25",
  },
  {
    id: "fact-work-right",
    category: "preference",
    title: localized("أهلية العمل", "Work eligibility"),
    detail: localized("لم يؤكدها المستخدم بعد", "Not yet confirmed by the user"),
    source: localized("لا يوجد مصدر", "No source"),
    status: "unconfirmed",
    updatedAt: "2026-08-04",
  },
  {
    id: "fact-location",
    category: "preference",
    title: localized("موقع العمل المفضل", "Preferred work location"),
    detail: localized("الرياض أو العمل الهجين", "Riyadh or hybrid"),
    source: localized("إدخال مباشر من المستخدم", "Direct user input"),
    status: "confirmed",
    updatedAt: "2026-07-25",
  },
];

export const demoJobs: Job[] = [
  {
    id: "demo-data-analyst",
    title: localized("محلل بيانات مبتدئ", "Junior Data Analyst"),
    company: localized("شركة تقنية سعودية", "Saudi Technology Co."),
    location: localized("الرياض", "Riyadh"),
    source: localized("منشور الشركة", "Company listing"),
    freshness: localized("قبل يومين", "2 days ago"),
    employmentType: localized("دوام كامل", "Full-time"),
    coverage: 87,
    recommendation: "apply_now",
    readiness: "high",
    confidence: "medium",
    description: localized(
      "نبحث عن محلل بيانات مبتدئ يجيد SQL وPython وPower BI. يفضّل وجود خبرة في قطاع التجزئة ومهارات تواصل جيدة.",
      "We are looking for a junior data analyst proficient in SQL, Python, and Power BI. Retail experience and strong communication skills are preferred."
    ),
    originalUrl: "https://example.com/demo-job",
    isDemo: true,
    requirements: [
      {
        id: "req-sql",
        category: "skill",
        label: localized("SQL", "SQL"),
        kind: "essential",
        weight: 25,
        status: "supported",
        evidence: localized("مشروع لوحة مبيعات", "Sales dashboard project"),
        evidenceFactId: "fact-project-dashboard",
        explanation: localized("ذُكر SQL صراحة في ملف المشروع المؤكد.", "SQL is explicitly stated in the confirmed project file."),
      },
      {
        id: "req-python",
        category: "skill",
        label: localized("Python", "Python"),
        kind: "essential",
        weight: 25,
        status: "supported",
        evidence: localized("تدريب تعاوني في تحليل البيانات", "Data analytics internship"),
        evidenceFactId: "fact-python-internship",
        explanation: localized("استخدام Python موثق في خبرة التدريب.", "Python use is documented in the internship experience."),
      },
      {
        id: "req-powerbi",
        category: "certification",
        label: localized("Power BI", "Power BI"),
        kind: "essential",
        weight: 20,
        status: "supported",
        evidence: localized("شهادة Power BI", "Power BI certificate"),
        evidenceFactId: "fact-powerbi",
        explanation: localized("هناك شهادة إتمام مؤكدة ومشروع مرتبط.", "A verified completion certificate and relevant project are available."),
      },
      {
        id: "req-communication",
        category: "skill",
        label: localized("مهارات التواصل", "Communication skills"),
        kind: "essential",
        weight: 15,
        status: "unknown",
        explanation: localized("الوصف يطلبها، لكن الملف لا يتضمن مثالًا يمكن التحقق منه.", "The role asks for it, but the profile has no verifiable example."),
      },
      {
        id: "req-visualization",
        category: "skill",
        label: localized("تصور البيانات المتقدم", "Advanced data visualization"),
        kind: "preferred",
        weight: 10,
        status: "partial",
        evidence: localized("مشروع تحليل العملاء", "Customer analysis project"),
        explanation: localized("يوجد استخدام أساسي، دون دليل على تقنيات متقدمة.", "Basic use is present, without evidence of advanced techniques."),
      },
      {
        id: "req-retail",
        category: "experience",
        label: localized("خبرة في قطاع التجزئة", "Retail sector experience"),
        kind: "preferred",
        weight: 5,
        status: "unsupported",
        explanation: localized("لا يوجد دليل يدعم خبرة في قطاع التجزئة.", "There is no evidence supporting retail sector experience."),
      },
    ],
  },
  {
    id: "demo-product-designer",
    title: localized("مصمم منتجات", "Product Designer"),
    company: localized("لينكدإن — عرض تجريبي", "LinkedIn — demo listing"),
    location: localized("الرياض", "Riyadh"),
    source: localized("إدخال يدوي", "Manual entry"),
    freshness: localized("قبل يوم", "1 day ago"),
    employmentType: localized("دوام كامل", "Full-time"),
    coverage: 79,
    recommendation: "improve_then_apply",
    readiness: "medium",
    confidence: "medium",
    description: localized("دور تصميم منتجات رقمية مع تركيز على البحث وتجربة المستخدم.", "Digital product design role focused on research and user experience."),
    isDemo: true,
    requirements: [],
  },
  {
    id: "demo-software-engineer",
    title: localized("مهندس برمجيات", "Software Engineer"),
    company: localized("موقع الشركة — عرض تجريبي", "Company site — demo listing"),
    location: localized("جدة", "Jeddah"),
    source: localized("إدخال يدوي", "Manual entry"),
    freshness: localized("قبل 3 أيام", "3 days ago"),
    employmentType: localized("دوام كامل", "Full-time"),
    coverage: 74,
    recommendation: "improve_then_apply",
    readiness: "medium",
    confidence: "low",
    description: localized("فرصة تجريبية لمهندس برمجيات في بداية المسار.", "Demo opportunity for an early-career software engineer."),
    isDemo: true,
    requirements: [],
  },
];

export const demoApplications: Application[] = [
  {
    id: "app-1",
    jobId: "demo-data-analyst",
    role: localized("محلل بيانات مبتدئ", "Junior Data Analyst"),
    company: localized("شركة تقنية سعودية", "Saudi Technology Co."),
    location: localized("الرياض", "Riyadh"),
    stage: "ready",
    updatedAt: "2026-08-05",
    nextAction: localized("راجع الحزمة وافتح صفحة التقديم", "Review the package and open the application page"),
    documentVersion: "CV-DA-v2",
    isDemo: true,
  },
  {
    id: "app-2",
    jobId: "demo-product-designer",
    role: localized("مصمم منتجات", "Product Designer"),
    company: localized("استوديو نواة", "Nawa Studio"),
    location: localized("الرياض", "Riyadh"),
    stage: "saved",
    updatedAt: "2026-08-04",
    nextAction: localized("أضف دليلًا على بحث المستخدم", "Add evidence of user research"),
    documentVersion: "—",
    isDemo: true,
  },
  {
    id: "app-3",
    jobId: "demo-data-analyst",
    role: localized("محلل أعمال", "Business Analyst"),
    company: localized("شركة أفق", "Ofuq Co."),
    location: localized("الرياض", "Riyadh"),
    stage: "applied",
    updatedAt: "2026-08-01",
    nextAction: localized("متابعة بعد يومين", "Follow up in two days"),
    documentVersion: "CV-BA-v1",
    isDemo: true,
  },
  {
    id: "app-4",
    jobId: "demo-software-engineer",
    role: localized("محلل ذكاء أعمال", "BI Analyst"),
    company: localized("مدار الرقمية", "Madar Digital"),
    location: localized("جدة", "Jeddah"),
    stage: "interview",
    updatedAt: "2026-08-06",
    nextAction: localized("حضّر أمثلة مشروع لوحة المبيعات", "Prepare sales dashboard project examples"),
    documentVersion: "CV-BI-v3",
    isDemo: true,
  },
];

export const profileCompletion = 82;
