"""Initial explicit evidence-first schema.

Revision ID: 20260806_0001
Revises: None
Create Date: 2026-08-06 20:45:30.264206
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260806_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "career_profiles",
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("headline", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "preferred_language",
            sa.Enum("ar", "en", name="preferred_language", native_enum=False),
            nullable=False,
        ),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("years_experience", sa.Float(), nullable=True),
        sa.Column("completed_fact_categories", sa.JSON(), nullable=False),
        sa.Column("evidence_revision", sa.Integer(), nullable=False),
        sa.Column("deletion_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_career_profiles")),
    )
    with op.batch_alter_table("career_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_career_profiles_owner_id"), ["owner_id"], unique=True)

    op.create_table(
        "deletion_receipts",
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_counts", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_receipts")),
    )
    op.create_table(
        "source_policies",
        sa.Column("source_key", sa.String(length=120), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "intake_method",
            sa.Enum(
                "manual", "user_upload", "licensed_feed", name="intake_method", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("permission_basis", sa.String(length=1000), nullable=False),
        sa.Column("terms_reviewed_at", sa.Date(), nullable=True),
        sa.Column("can_search_automatically", sa.Boolean(), nullable=False),
        sa.Column("can_fetch_details", sa.Boolean(), nullable=False),
        sa.Column("can_apply_automatically", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_policies")),
    )
    with op.batch_alter_table("source_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_policies_source_key"), ["source_key"], unique=True
        )

    op.create_table(
        "evidence_sources",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "manual",
                "cv_upload",
                "linkedin_export",
                "licensed_feed",
                name="source_kind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=True),
        sa.Column("source_locator", sa.String(length=1000), nullable=True),
        sa.Column("source_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["career_profiles.id"],
            name=op.f("fk_evidence_sources_profile_id_career_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_sources")),
    )
    with op.batch_alter_table("evidence_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_sources_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "jobs",
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("source_policy_id", sa.Uuid(), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column(
            "intake_method",
            sa.Enum(
                "manual",
                "user_upload",
                "licensed_feed",
                name="job_intake_method",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("company", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("posted_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("requirements_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requirements_reviewed_by_owner_id", sa.String(length=255), nullable=True),
        sa.Column("requirements_review_hash", sa.String(length=64), nullable=True),
        sa.Column("requirements_revision", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_policy_id"],
            ["source_policies.id"],
            name=op.f("fk_jobs_source_policy_id_source_policies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("owner_id", "content_hash", name="uq_jobs_owner_hash"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_source_policy_id"), ["source_policy_id"], unique=False
        )

    op.create_table(
        "career_facts",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "identity",
                "education",
                "experience",
                "certification",
                "skill",
                "project",
                "language",
                "achievement",
                "preference",
                "eligibility",
                name="fact_category",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=500), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("structured_value", sa.JSON(), nullable=False),
        sa.Column("source_excerpt", sa.Text(), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "extracted",
                "confirmed",
                "unconfirmed",
                name="verification_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_correction_reason", sa.Text(), nullable=True),
        sa.Column("user_corrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_extraction", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["career_profiles.id"],
            name=op.f("fk_career_facts_profile_id_career_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["evidence_sources.id"],
            name=op.f("fk_career_facts_source_id_evidence_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_career_facts")),
    )
    with op.batch_alter_table("career_facts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_career_facts_profile_id"), ["profile_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_career_facts_source_id"), ["source_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_career_facts_verification_status"), ["verification_status"], unique=False
        )

    op.create_table(
        "document_versions",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("base_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("cv", "cover_letter", name="document_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.Enum("ar", "en", name="document_language", native_enum=False),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "reviewed", "export_ready", name="document_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("diff_summary", sa.JSON(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_owner_id", sa.String(length=255), nullable=True),
        sa.Column("review_hash", sa.String(length=64), nullable=True),
        sa.Column("evidence_revision_at_review", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_version_id"],
            ["document_versions.id"],
            name=op.f("fk_document_versions_base_version_id_document_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_document_versions_job_id_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["career_profiles.id"],
            name=op.f("fk_document_versions_profile_id_career_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
    )
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_versions_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_document_versions_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "job_requirements",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "skill",
                "experience",
                "education",
                "certification",
                "language",
                "location",
                "eligibility",
                "other",
                name="requirement_category",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "importance",
            sa.Enum("mandatory", "preferred", name="requirement_importance", native_enum=False),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.String(length=500), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("needs_user_review", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("user_added", sa.Boolean(), nullable=False),
        sa.Column("user_correction_reason", sa.Text(), nullable=True),
        sa.Column("user_corrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_extraction", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_requirements_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_requirements")),
    )
    with op.batch_alter_table("job_requirements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_requirements_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_job_requirements_normalized_value"), ["normalized_value"], unique=False
        )

    op.create_table(
        "match_analyses",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("coverage_score", sa.Integer(), nullable=False),
        sa.Column("mandatory_coverage_score", sa.Integer(), nullable=False),
        sa.Column(
            "readiness_band",
            sa.Enum("low", "medium", "high", name="readiness_band", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "confidence_band",
            sa.Enum("low", "medium", "high", name="confidence_band", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "decision",
            sa.Enum(
                "apply_now",
                "improve_then_apply",
                "low_return",
                "need_information",
                name="apply_decision",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.JSON(), nullable=False),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidation_reason", sa.String(length=500), nullable=True),
        sa.Column("evidence_revision", sa.Integer(), nullable=False),
        sa.Column("requirements_revision", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_match_analyses_job_id_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["career_profiles.id"],
            name=op.f("fk_match_analyses_profile_id_career_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_analyses")),
    )
    with op.batch_alter_table("match_analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_match_analyses_invalidated_at"), ["invalidated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_match_analyses_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_match_analyses_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "applications",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=True),
        sa.Column("cv_document_id", sa.Uuid(), nullable=True),
        sa.Column("cover_letter_document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "saved",
                "preparing",
                "ready",
                "submitted",
                "interview",
                "rejected",
                "offer",
                "withdrawn",
                name="application_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_action_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["match_analyses.id"],
            name=op.f("fk_applications_analysis_id_match_analyses"),
        ),
        sa.ForeignKeyConstraint(
            ["cover_letter_document_id"],
            ["document_versions.id"],
            name=op.f("fk_applications_cover_letter_document_id_document_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["cv_document_id"],
            ["document_versions.id"],
            name=op.f("fk_applications_cv_document_id_document_versions"),
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_applications_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["career_profiles.id"],
            name=op.f("fk_applications_profile_id_career_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("profile_id", "job_id", name="uq_applications_profile_job"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_applications_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_applications_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "document_claims",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "claim_type",
            sa.Enum(
                "identity",
                "experience",
                "education",
                "skill",
                "achievement",
                "project",
                "certification",
                "language",
                "preference",
                "salutation",
                "intent",
                "transition",
                name="claim_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("supported", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document_versions.id"],
            name=op.f("fk_document_claims_document_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_claims")),
    )
    with op.batch_alter_table("document_claims", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_claims_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "requirement_matches",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_fact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "matched", "missing", "unknown", name="requirement_match_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("earned_weight", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["match_analyses.id"],
            name=op.f("fk_requirement_matches_analysis_id_match_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_fact_id"],
            ["career_facts.id"],
            name=op.f("fk_requirement_matches_evidence_fact_id_career_facts"),
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["job_requirements.id"],
            name=op.f("fk_requirement_matches_requirement_id_job_requirements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_matches")),
    )
    with op.batch_alter_table("requirement_matches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_matches_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_requirement_matches_evidence_fact_id"),
            ["evidence_fact_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_requirement_matches_requirement_id"), ["requirement_id"], unique=False
        )

    op.create_table(
        "claim_evidence",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("fact_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["document_claims.id"],
            name=op.f("fk_claim_evidence_claim_id_document_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fact_id"], ["career_facts.id"], name=op.f("fk_claim_evidence_fact_id_career_facts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_evidence")),
        sa.UniqueConstraint("claim_id", "fact_id", name="uq_claim_evidence_claim_fact"),
    )
    with op.batch_alter_table("claim_evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claim_evidence_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_claim_evidence_fact_id"), ["fact_id"], unique=False)

    op.create_table(
        "outcomes",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "screening",
                "interview",
                "rejection",
                "offer",
                "withdrawal",
                name="outcome_kind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_by_user", sa.Boolean(), nullable=False),
        sa.Column("qualified_human_interview", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_outcomes_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outcomes")),
    )
    with op.batch_alter_table("outcomes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_outcomes_application_id"), ["application_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outcomes_application_id"))

    op.drop_table("outcomes")
    with op.batch_alter_table("claim_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claim_evidence_fact_id"))
        batch_op.drop_index(batch_op.f("ix_claim_evidence_claim_id"))

    op.drop_table("claim_evidence")
    with op.batch_alter_table("requirement_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_matches_requirement_id"))
        batch_op.drop_index(batch_op.f("ix_requirement_matches_evidence_fact_id"))
        batch_op.drop_index(batch_op.f("ix_requirement_matches_analysis_id"))

    op.drop_table("requirement_matches")
    with op.batch_alter_table("document_claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_claims_document_id"))

    op.drop_table("document_claims")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_profile_id"))
        batch_op.drop_index(batch_op.f("ix_applications_job_id"))

    op.drop_table("applications")
    with op.batch_alter_table("match_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_match_analyses_profile_id"))
        batch_op.drop_index(batch_op.f("ix_match_analyses_job_id"))
        batch_op.drop_index(batch_op.f("ix_match_analyses_invalidated_at"))

    op.drop_table("match_analyses")
    with op.batch_alter_table("job_requirements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_requirements_normalized_value"))
        batch_op.drop_index(batch_op.f("ix_job_requirements_job_id"))

    op.drop_table("job_requirements")
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_versions_profile_id"))
        batch_op.drop_index(batch_op.f("ix_document_versions_job_id"))

    op.drop_table("document_versions")
    with op.batch_alter_table("career_facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_career_facts_verification_status"))
        batch_op.drop_index(batch_op.f("ix_career_facts_source_id"))
        batch_op.drop_index(batch_op.f("ix_career_facts_profile_id"))

    op.drop_table("career_facts")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_source_policy_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_owner_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("evidence_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_sources_profile_id"))

    op.drop_table("evidence_sources")
    with op.batch_alter_table("source_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_policies_source_key"))

    op.drop_table("source_policies")
    op.drop_table("deletion_receipts")
    with op.batch_alter_table("career_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_career_profiles_owner_id"))

    op.drop_table("career_profiles")
    # ### end Alembic commands ###
